In [1]:
pip install kagglehub

Requirement already satisfied: kagglehub in .\anaconda3\Lib\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in .\anaconda3\Lib\site-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in .\anaconda3\Lib\site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in .\anaconda3\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in .\anaconda3\Lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in .\anaconda3\Lib\site-packages (from kagglehub) (4.68.2)
Requirement already satisfied: protobuf in .\anaconda3\Lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (6.33.5)
Requirement already satisfied: charset_normalizer<4,>=2 in .\anaconda3\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\anaconda3\Lib\site-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\anaconda3\Lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\anaconda3\Lib\site-packages (from requests->kagglehub) (2026.6.17)
Requirement already satisfied: colorama in .\anaconda3\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nehaprabhavalkar/indian-food-101")

print("Path to dataset files:", path)

Downloading to C:\Users\hp\.cache\kagglehub\datasets\nehaprabhavalkar\indian-food-101\2.archive...

100%|██████████| 6.79k/6.79k [00:00<00:00, 80.4kB/s]

Extracting files...
Path to dataset files: C:\Users\hp\.cache\kagglehub\datasets\nehaprabhavalkar\indian-food-101\versions\2

In [5]:
import pandas as pd
import os

csv_file = os.path.join(path, "indian_food.csv")

df = pd.read_csv(csv_file)

df.head()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East

In [6]:
df.head(25)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East
5,Imarti,"Sugar syrup, lentil flour",vegetarian,10,50,sweet,dessert,West Bengal,East
6,Jalebi,"Maida, corn flour, baking soda, vinegar, curd,...",vegetarian,10,50,sweet,dessert,Uttar Pradesh,North
7,Kaju katli,"Cashews, ghee, cardamom, sugar",vegetarian,10,20,sweet,dessert,-1,-1
8,Kalakand,"Milk, cottage cheese, sugar",vegetarian,20,30,sweet,dessert,West Bengal,East
9,Kheer,"Milk, rice, sugar, dried fruits",vegetarian,10,40,sweet,dessert,-1,-1
10,Laddu,"Gram flour, ghee, sugar",vegetarian,10,40,sweet,dessert,-1,-1
11,Lassi,"Yogurt, milk, nuts, sugar",vegetarian,5,5,sweet,dessert,Punjab,North
12,Nankhatai,"Refined flour, besan, ghee, powdered sugar, yo...",vegetarian,20,30,sweet,dessert,-1,-1
13,Petha,"Firm white pumpkin, sugar, kitchen lime, alum ...",vegetarian,10,30,sweet,dessert,Uttar Pradesh,North
14,Phirni,"Rice, sugar, nuts",vegetarian,30,20,sweet,dessert,Odisha,East
15,Rabri,"Condensed milk, sugar, spices, nuts",vegetarian,10,45,sweet,dessert,Uttar Pradesh,North
16,Sheera,"Semolina, ghee, nuts, milk",vegetarian,10,25,sweet,dessert,Maharashtra,West
17,Singori,"Khoa, coconut, molu leaf",vegetarian,10,20,sweet,dessert,Uttarakhand,North
18,Sohan halwa,"Corn flour, ghee, dry fruits",vegetarian,10,60,sweet,dessert,Uttar Pradesh,North
19,Sohan papdi,"Gram flour, ghee, sugar, milk, cardamom",vegetarian,-1,60,sweet,dessert,Maharashtra,West
20,Chhena jalebi,"Chhena, sugar, ghee",vegetarian,10,50,sweet,dessert,Odisha,East
21,Chhena kheeri,"Chhena, sugar, milk",vegetarian,-1,60,sweet,dessert,Odisha,East
22,Chhena poda,"Sugar, chenna cheese",vegetarian,10,45,sweet,dessert,Odisha,East
23,Cham cham,"Flour, cream, sugar, saffron, lemon juice, coc...",vegetarian,40,60,sweet,dessert,West Bengal,East
24,Kheer sagar,"Chenna, condensed milk, sugar, saffron, cardamom",vegetarian,25,60,sweet,dessert,Odisha,East

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            255 non-null    str
 1   ingredients     255 non-null    str
 2   diet            255 non-null    str
 3   prep_time       255 non-null    int64
 4   cook_time       255 non-null    int64
 5   flavor_profile  255 non-null    str
 6   course          255 non-null    str
 7   state           255 non-null    str
 8   region          254 non-null    str
dtypes: int64(2), str(7)
memory usage: 41.7 KB

In [8]:
df.tail()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
250,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5,30,sweet,dessert,Assam,North East
251,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20,60,sweet,dessert,Goa,West
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,-1,-1,sweet,dessert,Jammu & Kashmir,North
253,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20,45,sweet,dessert,Madhya Pradesh,Central
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,-1,-1,sweet,dessert,Goa,West

In [9]:
df.tail(15)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
240,Konir Dom,"Aloo, tomatoes, mustard oil, bay leaf, cinnamo...",non vegetarian,-1,-1,spicy,main course,Assam,North East
241,Koldil Duck,"Rice flour, mutton, banana, gram flour, olive ...",non vegetarian,-1,-1,spicy,main course,Assam,North East
242,Masor Koni,"Fish roe, pumpkin flowers, mustard oil, turmer...",non vegetarian,-1,-1,spicy,main course,Assam,North East
243,Mishti Chholar Dal,"Chana dal, fresh coconut, ginger, cinnamon, ra...",vegetarian,10,30,sweet,main course,West Bengal,East
244,Pakhala,"Curd, cooked rice, curry leaves, dry chilli",vegetarian,-1,-1,-1,main course,Odisha,East
245,Pani Pitha,"Tea leaves, white sesame seeds, dry coconut, s...",vegetarian,10,20,-1,main course,Assam,North East
246,Payokh,"Basmati rice, rose water, sugar, clarified but...",vegetarian,-1,-1,sweet,dessert,Assam,North East
247,Prawn malai curry,"Coconut milk, prawns, garlic, turmeric, sugar",non vegetarian,15,50,spicy,main course,West Bengal,East
248,Red Rice,"Red pepper, red onion, butter, watercress, oli...",vegetarian,-1,-1,-1,main course,-1,-1
249,Shukto,"Green beans, bitter gourd, ridge gourd, banana...",vegetarian,10,20,spicy,main course,West Bengal,East
250,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5,30,sweet,dessert,Assam,North East
251,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20,60,sweet,dessert,Goa,West
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,-1,-1,sweet,dessert,Jammu & Kashmir,North
253,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20,45,sweet,dessert,Madhya Pradesh,Central
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,-1,-1,sweet,dessert,Goa,West

In [10]:
df.shape

(255, 9)

In [11]:
df.columns

Index(['name', 'ingredients', 'diet', 'prep_time', 'cook_time',
       'flavor_profile', 'course', 'state', 'region'],
      dtype='str')

In [12]:
df.describe()

        prep_time   cook_time
count  255.000000  255.000000
mean    31.105882   34.529412
std     72.554409   48.265650
min     -1.000000   -1.000000
25%     10.000000   20.000000
50%     10.000000   30.000000
75%     20.000000   40.000000
max    500.000000  720.000000

In [13]:
df.describe(include='all')

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
count,255,255,255,255.000000,255.000000,255,255,255,254
unique,255,252,2,NaN,NaN,5,4,25,7
top,Balu shahi,"Gram flour, ghee, sugar",vegetarian,NaN,NaN,spicy,main course,Gujarat,West
freq,1,2,226,NaN,NaN,133,129,35,74
mean,NaN,NaN,NaN,31.105882,34.529412,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,72.554409,48.265650,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,-1.000000,-1.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,10.000000,20.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,10.000000,30.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,20.000000,40.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,500.000000,720.000000,NaN,NaN,NaN,NaN

In [17]:
df["cook_time"].mean()

np.float64(34.529411764705884)

In [16]:
df["cook_time"].max()

np.int64(720)

In [18]:
df["prep_time"].median()

np.float64(10.0)

In [21]:
df["diet"].mode()

0    vegetarian
Name: diet, dtype: str

In [22]:
df["region"].nunique()

7

In [23]:
df["cook_time"].quantile(0.75)

np.float64(40.0)

In [24]:
df["prep_time"].skew()

np.float64(4.636300925063016)

In [25]:
df.groupby("diet")["prep_time"].mean()

diet
non vegetarian    27.068966
vegetarian        31.623894
Name: prep_time, dtype: float64

In [26]:
df.groupby("flavor_profile")["cook_time"].median()

flavor_profile
-1        20.0
bitter    35.0
sour      10.0
spicy     30.0
sweet     30.0
Name: cook_time, dtype: float64

In [27]:
df.isna()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
250,False,False,False,False,False,False,False,False,False
251,False,False,False,False,False,False,False,False,False
252,False,False,False,False,False,False,False,False,False
253,False,False,False,False,False,False,False,False,False
254,False,False,False,False,False,False,False,False,False

In [28]:
df.isna().sum()

name              0
ingredients       0
diet              0
prep_time         0
cook_time         0
flavor_profile    0
course            0
state             0
region            1
dtype: int64

In [29]:
df[df.isna().any(axis=1)]

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
110,Panjeeri,"Whole wheat flour, musk melon seeds, poppy see...",vegetarian,10,25,sweet,dessert,Uttar Pradesh,NaN

In [30]:
df.notna()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
250,True,True,True,True,True,True,True,True,True
251,True,True,True,True,True,True,True,True,True
252,True,True,True,True,True,True,True,True,True
253,True,True,True,True,True,True,True,True,True
254,True,True,True,True,True,True,True,True,True

In [31]:
df["diet"].str.strip()

0      vegetarian
1      vegetarian
2      vegetarian
3      vegetarian
4      vegetarian
          ...
250    vegetarian
251    vegetarian
252    vegetarian
253    vegetarian
254    vegetarian
Name: diet, Length: 255, dtype: str

In [32]:
df["course"].str.startswith("Main")

0      False
1      False
2      False
3      False
4      False
       ...
250    False
251    False
252    False
253    False
254    False
Name: course, Length: 255, dtype: bool

In [33]:
df["region"].str.title()

0            East
1            West
2           North
3            West
4            East
          ...
250    North East
251          West
252         North
253       Central
254          West
Name: region, Length: 255, dtype: str

In [34]:
df["name"].str.upper()

0          BALU SHAHI
1              BOONDI
2      GAJAR KA HALWA
3              GHEVAR
4         GULAB JAMUN
            ...
250         TIL PITHA
251           BEBINCA
252            SHUFTA
253         MAWA BATI
254            PINACA
Name: name, Length: 255, dtype: str

In [35]:
df["state"].str.split(",")

0          [West Bengal]
1            [Rajasthan]
2               [Punjab]
3            [Rajasthan]
4          [West Bengal]
             ...
250              [Assam]
251                [Goa]
252    [Jammu & Kashmir]
253     [Madhya Pradesh]
254                [Goa]
Name: state, Length: 255, dtype: object

In [36]:
df["diet"].str.isalpha()

0      True
1      True
2      True
3      True
4      True
       ...
250    True
251    True
252    True
253    True
254    True
Name: diet, Length: 255, dtype: bool

In [37]:
df["state"].str.slice(0, 5)

0      West
1      Rajas
2      Punja
3      Rajas
4      West
       ...
250    Assam
251      Goa
252    Jammu
253    Madhy
254      Goa
Name: state, Length: 255, dtype: str

In [38]:
df["course"].str.repeat(2)

0      dessertdessert
1      dessertdessert
2      dessertdessert
3      dessertdessert
4      dessertdessert
            ...
250    dessertdessert
251    dessertdessert
252    dessertdessert
253    dessertdessert
254    dessertdessert
Name: course, Length: 255, dtype: str

In [39]:
df[df["name"].str.startswith("A")].groupby("course")["prep_time"].mean()

course
dessert         11.666667
main course     10.625000
snack          150.000000
Name: prep_time, dtype: float64

In [40]:
df.sort_values("cook_time", ascending=False)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
62,Shrikhand,"Curd, sugar, saffron, cardamom",vegetarian,10,720,sweet,dessert,Maharashtra,West
27,Malapua,"Yoghurt, refined flour, ghee, fennel seeds",vegetarian,10,120,sweet,dessert,Bihar,North
75,Biryani,"Chicken thighs, basmati rice, star anise, swee...",non vegetarian,30,120,spicy,main course,Telangana,South
114,Pindi chana,"Fennel, tea bags, tomato, kasuri methi, cinnamon",vegetarian,500,120,spicy,main course,Punjab,North
115,Rajma chaval,"Red kidney beans, garam masala powder, ginger,...",vegetarian,15,90,spicy,main course,-1,North
...,...,...,...,...,...,...,...,...,...
242,Masor Koni,"Fish roe, pumpkin flowers, mustard oil, turmer...",non vegetarian,-1,-1,spicy,main course,Assam,North East
240,Konir Dom,"Aloo, tomatoes, mustard oil, bay leaf, cinnamo...",non vegetarian,-1,-1,spicy,main course,Assam,North East
248,Red Rice,"Red pepper, red onion, butter, watercress, oli...",vegetarian,-1,-1,-1,main course,-1,-1
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,-1,-1,sweet,dessert,Jammu & Kashmir,North
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,-1,-1,sweet,dessert,Goa,West

In [41]:
df.groupby("state")[["prep_time","cook_time"]].agg(["mean","min","max"])

                  prep_time           cook_time
                       mean min  max       mean min  max
state
-1                63.083333  -1  360  35.041667  -1   90
Andhra Pradesh    61.000000   5  240  37.500000  15   75
Assam              5.714286  -1   20  14.285714  -1   40
Bihar             21.666667  10   45  66.666667  20  120
Chhattisgarh      10.000000  10   10  60.000000  60   60
Goa                9.666667  -1   20  33.000000  -1   60
Gujarat           13.742857  -1   35  26.485714  -1   60
Haryana           10.000000  10   10  60.000000  60   60
Jammu & Kashmir    9.500000  -1   20  24.500000  -1   50
Karnataka         60.833333   5  180  44.166667  20   60
Kerala            71.750000  -1  495  29.250000  -1   60
Madhya Pradesh    15.000000  10   20  42.500000  40   45
Maharashtra       15.400000  -1   70  51.100000  -1  720
Manipur          119.500000  -1  240  22.000000  -1   45
NCT of Delhi      10.000000  10   10  35.000000  35   35
Nagaland           5.000000   5    5  15.000000  15   15
Odisha            12.571429  -1   30  37.714286  -1   60
Punjab            48.750000   5  500  37.343750   5  120
Rajasthan         22.833333  10   80  40.000000  20   90
Tamil Nadu        14.350000  -1  120  22.850000  -1   90
Telangana         16.000000  10   30  44.000000  20  120
Tripura           -1.000000  -1   -1  -1.000000  -1   -1
Uttar Pradesh     16.111111  10   30  43.333333  25   60
Uttarakhand       10.000000  10   10  20.000000  20   20
West Bengal       45.125000  -1  480  37.416667  -1   90